### ISSUE TITLE
dictionary changed size during iteration for self._metrics in ThreadStats

### ISSUE THREAD

**Issue by leozc** [DataDog/datadogpy#142]
While using **ThreadStats** client under uwsgi:

> Error flushing metrics and events
> dictionary changed size during iteration
> on 
> Line: datadog/threadstats/metrics.py in flush at line 142
> past_intervals = [i for i in self._metrics if i < interval] 

The root cause is while iterating, new items are being added to self._metrics

**Comment by yannmh** [comment]
Thanks for reporting the issue @leozc. We'll work on a fix for the next release !

**Comment by yannmh** [comment]
Fixed with https://github.com/DataDog/datadogpy/pull/151

**Comment by overset** [comment]
This is a regression in python3 that is susceptible to the keys() view object changing which is not threadsafe. In python3 with latest `datadogpy` we're still getting:

```
RuntimeError: dictionary changed size during iteration
  File "datadog/threadstats/base.py", line 307, in flush
    metrics, dists = self._get_aggregate_metrics_and_dists(timestamp or time())
  File "datadog/threadstats/base.py", line 348, in _get_aggregate_metrics_and_dists
    rolled_up_metrics = self._metric_aggregator.flush(flush_time)
  File "datadog/threadstats/metrics.py", line 173, in flush
    past_intervals = [i for i in self._metrics.keys() if i < interval]
  File "datadog/threadstats/metrics.py", line 173, in <listcomp>
    past_intervals = [i for i in self._metrics.keys() if i < interval]
```

This is related to the python3 [view object](https://docs.python.org/3.7/library/stdtypes.html?highlight=keys#dict-views) that `.keys()` returns:

> The objects returned by dict.keys(), dict.values() and dict.items() are view objects. They provide a dynamic view on the dictionary’s entries, which means that when the dictionary changes, the view reflects these changes.

py2.7 https://docs.python.org/2/library/stdtypes.html?highlight=keys#dict.keys
```
keys()
Return a copy of the dictionary’s list of keys. See the note for dict.items().
```
py3.7 https://docs.python.org/3.7/library/stdtypes.html?highlight=keys#dict.keys
```
keys()
Return a new view of the dictionary’s keys. See the documentation of view objects.
```

Here's a quick script to repro similar logic as in https://github.com/DataDog/datadogpy/blob/master/datadog/threadstats/metrics.py#L173 that fails with python3 and works with python2:

```python
import threading

def prune(data):
    data.pop(1)

def print_half(data):
    print(len([i for i in data.keys() if i > len(data) / 2]))

data = {i: i for i in range(100000)}
threading.Thread(target=print_half, args=(data, )).start()
threading.Thread(target=prune, args=(data, )).start()
```

It seems that https://github.com/DataDog/datadogpy/pull/151 only works for python2 and https://github.com/DataDog/datadogpy/pull/143 works for both python2 and python3.
